DROP TABLE MEMBER PURGE;
create table MEMBER(
	MEMBER_ID VARCHAR2(20) PRIMARY KEY,
	MEMBER_PW VARCHAR2(20) NOT NULL,
	MEMBER_NAME VARCHAR2(20) NOT NULL,
	MEMBER_JUMIN1 NUMBER NOT NULL,
	MEMBER_JUMIN2 NUMBER NOT NULL,
	MEMBER_EMAIL VARCHAR2(25) NOT NULL,
	MEMBER_EMAIL_GET VARCHAR2(25) NOT NULL,
	MEMBER_MOBILE VARCHAR2(13) NOT NULL,
	MEMBER_PHONE VARCHAR2(13) NOT NULL,
	MEMBER_ZIPCODE VARCHAR2(13) NOT NULL,
	MEMBER_ADDR1 VARCHAR2(50) NOT NULL,
	MEMBER_ADDR2 VARCHAR2(50) NOT NULL,
	MEMBER_ADMIN NUMBER NOT NULL,
	MEMBER_JOIN_DATE DATE NOT NULL
)
Select * from TOTAL_SCHEDULE where (sCHEDULE_APP_start_DATE >=to_date(20190101,'YYYY-MM-DD') and sCHEDULE_APP_end_DATE<to_date(20190201,'YYYY-MM-DD'))
select * from MEMBER;
delete from MEMBER;
Select * from TOTAL_SCHEDULE where MEMBER_ID = 'im' AND 
(
(sCHEDULE_APP_start_DATE >=to_date(20190101,'YYYY-MM-DD') and sCHEDULE_APP_end_DATE<to_date(20190201,'YYYY-MM-DD'))
OR 
(sCHEDULE_DAy >=to_date(20190101,'YYYY-MM-DD') and sCHEDULE_DAy<to_date(20190201,'YYYY-MM-DD'))
)

DROP TABLE SCHEDULE PURGE;
CREATE TABLE SCHEDULE(
	SCHEDULE_ID NUMBER PRIMARY KEY,	
	SCHEDULE_NAME VARCHAR2(200) NOT NULL,
	SCHEDULE_APP_START_DATE DATE,
	SCHEDULE_APP_END_DATE DATE,
	SCHEDULE_DAY DATE,
	SCHEDULE_REF_SITE VARCHAR2(50),
	SCHEDULE_MEMO VARCHAR2(500),
	SCHEDULE_MANAGER VARCHAR2(30)	
)
/*SCHEDULE 테이블명 변경, SCHEDULE_ID 숫자속성으로 변경*/
select * from tab;

select * from SCHEDULE;
delete from SCHEDULE;
SELECT * FROM SCHEDULE order BY SCHEDULE_APP_START_DATE;

SELECT NVL(MAX(SCHEDULE_ID),0) FROM SCHEDULE;
SELECT * FROM SCHEDULE;
DELETE * FROM SCHEDULE;

SELECT * FROM SCHEDULE;
/* SCHEDULE_MANAGER VARCHAR2(20)추가함*/
/*
DROP TABLE SCHEDULE_MEMBER PURGE;
CREATE TABLE SCHEDULE_MEMBER(
	SCHEDULE_MEMBER_ID VARCHAR2(20) PRIMARY KEY,
	SCHEDULE_NAME VARCHAR2(50) NOT NULL,
	SCHEDULE_START_DATE DATE,
	SCHEDULE_END_DATE DATE,
	SCHEDULE_DAY DATE,
	SCHEDULE_REF_SITE VARCHAR2(50),
	SCHEDULE_MEMO VARCHAR2(400)	
)
*/

DROP TABLE SCHEDULE_LIST PURGE;
CREATE table SCHEDULE_LIST(
	LIST_ID NUMBER(4) PRIMARY KEY,
	MEMBER_ID VARCHAR2(20) REFERENCES MEMBER(MEMBER_ID),
	SCHEDULE_ID number REFERENCES SCHEDULE(SCHEDULE_ID),	
	LIST_RESULT NUMBER(2)
)
/* LIST_RESULT NUMBER(2) 진행중0 완료1 */
select * from SCHEDULE_LIST;
delete from SCHEDULE_LIST;
insert into SCHEDULE_LIST values(	(SELECT NVL(MAX(list_id),0)+1 FROM SCHEDULE_list),'im',1,0);
insert into SCHEDULE_LIST values(	(SELECT NVL(MAX(list_id),0)+1 FROM SCHEDULE_list),'im',2,0);
insert into SCHEDULE_LIST values(	(SELECT NVL(MAX(list_id),0)+1 FROM SCHEDULE_list),'im',3,0);
insert into SCHEDULE_LIST values(	(SELECT NVL(MAX(list_id),0)+1 FROM SCHEDULE_list),'im',4,0);
insert into SCHEDULE_LIST values(	(SELECT NVL(MAX(list_id),0)+1 FROM SCHEDULE_list),'im',5,0);

DROP VIEW TOTAL_SCHEDULE;
create view TOTAL_SCHEDULE AS SELECT SL.MEMBER_ID MEMBER_ID,
															SC.SCHEDULE_NAME SCHEDULE_NAME, 
															SC.SCHEDULE_APP_START_DATE SCHEDULE_APP_START_DATE, 
															SC.SCHEDULE_APP_END_DATE SCHEDULE_APP_END_DATE, 
															SC.SCHEDULE_DAY SCHEDULE_DAY,
															SC.SCHEDULE_REF_SITE SCHEDULE_REF_SITE,
															SC.SCHEDULE_MEMO SCHEDULE_MEMO,
															SL.LIST_RESULT LIST_RESULT												
															
															FROM SCHEDULE SC, SCHEDULE_LIST SL WHERE SL.SCHEDULE_ID=SC.SCHEDULE_ID;   
SELECT * FROM TOTAL_SCHEDULE;
Select * from TOTAL_SCHEDULE where (sCHEDULE_APP_start_DATE >=to_date(20190101,'YYYY-MM-DD') and sCHEDULE_APP_end_DATE<to_date(20190201,'YYYY-MM-DD'))

SELECT * FROM TAB;
SELECT * from TOTAL_SCHEDULE where (sCHEDULE_APP_start_DATE >='2019-1-1' and sCHEDULE_APP_start_DATE <='2019-1-31');

DROP TABLE ZIPCODE;
CREATE TABLE ZIPCODE (
  ID NUMBER,
  ZIPCODE VARCHAR2(7),
  SIDO VARCHAR2(10),
  GUGUN VARCHAR2(30),
  DONG VARCHAR2(36),
  RI VARCHAR2(60),
  BUNJI VARCHAR2(50),
  PRIMARY KEY (ID)
);

select * from MEMBER;
select * from ZIPCODE;

